apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: my-state
  labels:
    app: my-state
spec:
  selector:
    matchLabels:
      app: my-state
  template:
    metadata:
      name: my-state
      labels:
        app: my-state
        env: devops
    spec:
      containers:
      - name: my-web
        image: mariadb
        ports:
        - name: dbport
          containerPort: 3306
        env:
        - name: APP-NAME
          value: myapp
        - name: MARIADB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: my-secrets
              key: password