# dockerfile to install tomcat in ubuntu
FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive
ENV TOMCAT_VERSION=9.0.113
ENV TOMCAT_HOME=/opt/tomcat

RUN apt-get update && \
    apt-get install -y openjdk-21-jdk curl tar && \
    rm -rf /var/lib/apt/lists/*

RUN curl -fsSL https://dlcdn.apache.org/tomcat/tomcat-9/v${TOMCAT_VERSION}/bin/apache-tomcat-${TOMCAT_VERSION}.tar.gz \
    | tar -xz -C /opt && \
    mv /opt/apache-tomcat-${TOMCAT_VERSION} ${TOMCAT_HOME}

WORKDIR ${TOMCAT_HOME}/bin

EXPOSE 8080

CMD ["./catalina.sh", "run"]